# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Measure.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Measure(object):
    def setupUi(self, Measure):
        Measure.setObjectName("Measure")
        Measure.resize(966, 616)
        self.centralwidget = QtWidgets.QWidget(Measure)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 42, 907, 530))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.state_all = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.state_all.setFont(font)
        self.state_all.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.state_all.setAlignment(QtCore.Qt.AlignCenter)
        self.state_all.setObjectName("state_all")
        self.verticalLayout.addWidget(self.state_all)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.state_camera_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.state_camera_label.setFont(font)
        self.state_camera_label.setAlignment(QtCore.Qt.AlignCenter)
        self.state_camera_label.setObjectName("state_camera_label")
        self.horizontalLayout.addWidget(self.state_camera_label)
        self.state_camera = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.state_camera.setFont(font)
        self.state_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.state_camera.setObjectName("state_camera")
        self.horizontalLayout.addWidget(self.state_camera)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.state_judge_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.state_judge_label.setFont(font)
        self.state_judge_label.setAlignment(QtCore.Qt.AlignCenter)
        self.state_judge_label.setObjectName("state_judge_label")
        self.horizontalLayout_2.addWidget(self.state_judge_label)
        self.state_judge = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.state_judge.setFont(font)
        self.state_judge.setAlignment(QtCore.Qt.AlignCenter)
        self.state_judge.setObjectName("state_judge")
        self.horizontalLayout_2.addWidget(self.state_judge)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.state_program_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.state_program_label.setFont(font)
        self.state_program_label.setAlignment(QtCore.Qt.AlignCenter)
        self.state_program_label.setObjectName("state_program_label")
        self.horizontalLayout_3.addWidget(self.state_program_label)
        self.state_program = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.state_program.setFont(font)
        self.state_program.setAlignment(QtCore.Qt.AlignCenter)
        self.state_program.setObjectName("state_program")
        self.horizontalLayout_3.addWidget(self.state_program)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.Test = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Test.setFont(font)
        self.Test.setObjectName("Test")
        self.verticalLayout_2.addWidget(self.Test)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Turn = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Turn.setFont(font)
        self.Turn.setMouseTracking(True)
        self.Turn.setAlignment(QtCore.Qt.AlignCenter)
        self.Turn.setFlat(False)
        self.Turn.setCheckable(False)
        self.Turn.setObjectName("Turn")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Turn)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Turn_3 = QtWidgets.QRadioButton(self.Turn)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Turn_3.setFont(font)
        self.Turn_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Turn_3.setObjectName("Turn_3")
        self.verticalLayout_3.addWidget(self.Turn_3)
        self.Turn_4 = QtWidgets.QRadioButton(self.Turn)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Turn_4.setFont(font)
        self.Turn_4.setObjectName("Turn_4")
        self.verticalLayout_3.addWidget(self.Turn_4)
        self.verticalLayout_4.addWidget(self.Turn)
        self.Start = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Start.setFont(font)
        self.Start.setObjectName("Start")
        self.verticalLayout_4.addWidget(self.Start)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.camera_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.camera_label.setFont(font)
        self.camera_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.camera_label.setAlignment(QtCore.Qt.AlignCenter)
        self.camera_label.setObjectName("camera_label")
        self.verticalLayout_6.addWidget(self.camera_label)
        self.color_frame = QtWidgets.QLabel(self.widget)
        self.color_frame.setMinimumSize(QtCore.QSize(640, 480))
        self.color_frame.setMaximumSize(QtCore.QSize(640, 480))
        self.color_frame.setText("")
        self.color_frame.setObjectName("color_frame")
        self.verticalLayout_6.addWidget(self.color_frame)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        Measure.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(Measure)
        self.statusBar.setSizeGripEnabled(True)
        self.statusBar.setObjectName("statusBar")
        Measure.setStatusBar(self.statusBar)
        self.turn_chooose = QtWidgets.QAction(Measure)
        self.turn_chooose.setObjectName("turn_chooose")

        self.retranslateUi(Measure)
        QtCore.QMetaObject.connectSlotsByName(Measure)

    def retranslateUi(self, Measure):
        _translate = QtCore.QCoreApplication.translate
        Measure.setWindowTitle(_translate("Measure", "NCDX-Measure"))
        self.state_all.setText(_translate("Measure", "设备状态"))
        self.state_camera_label.setText(_translate("Measure", "相机状态："))
        self.state_camera.setText(_translate("Measure", "已连接"))
        self.state_judge_label.setText(_translate("Measure", "裁判状态："))
        self.state_judge.setText(_translate("Measure", "已连接"))
        self.state_program_label.setText(_translate("Measure", "运行状态："))
        self.state_program.setText(_translate("Measure", "准备就绪"))
        self.Test.setText(_translate("Measure", "设备检测"))
        self.Turn.setTitle(_translate("Measure", "轮次选择"))
        self.Turn_3.setText(_translate("Measure", "第三轮"))
        self.Turn_4.setText(_translate("Measure", "第四轮"))
        self.Start.setText(_translate("Measure", "开始测量"))
        self.camera_label.setText(_translate("Measure", "相机画面"))
        self.turn_chooose.setText(_translate("Measure", "轮次选择"))

